### PR TITLE
Prepare for 1.0.2 release

### LINKED ISSUE #89: New release
The update to `plug_crypto` to `1.2.0` (https://github.com/duffelhq/paginator/commit/268a97d68092b46e65aab278b2fb93facfca2fc8) has been merged one month ago but it's not included in any release, and we have to fallback to use the git dependency.

Maybe you can do a release with a patch version (`1.0.2`) to include it in a hex release?

### PR DESCRIPTION
**Pull request by sgerrand**
💁 These changes prepare this package for a release of version 1.0.2.

Closes #89

### CODE REVIEW

**Comment by warmwaffles** [comment]
What is the status on this?

**Comment by sgerrand** [comment]
👋 @warmwaffles: I plan on releasing this change today.

**Review by jesse-c — APPROVED** [review]
LGTM

**Review by nlopes — APPROVED** [review]

**Comment by sgerrand** [comment]
🗣️ @warmwaffles: I've just released [version 1.0.2 to Hex.pm](https://hex.pm/packages/paginator/1.0.2).

**Pull request merged**
